Changes to config file location
brainglobe/bg-atlasapi pull request #111
Opened 2021-12-20 19:31 UTC by chrisroat

Change config file directory.  Default directory changed from within site-packages to <HOME>/.config/brainglobe .   User can override with env var BRAINGLOBE_CONFIG_DIR.

Add config dir parameter to BrainGlobeAtlas

Fixed bug in config.write_config_value where config file was written to default location even if custom path passed in.

This change allows the caller to override the config directory in code, which takes precedence over the default location and the BRAINGLOBE_CONFIG_DIR variables.  Clients can use this to set the config dir via their command-line flags.

2021-12-28 17:11 UTC, adamltyson commented
Thanks @chrisroat! This looks fine to me. If you could just ensure the tests pass - I think you'll just need to run black:
```
pip install -e .[dev]
black ./
```

Happy to merge when you are @vigji, @FedeClaudi.

2021-12-31 04:42 UTC, chrisroat commented
Added commit to blacken.

2021-12-31 08:19 UTC, vigji commented
Looks good to me! Definitively better this way. Thanks @chrisroat, and sorry for the delayed review! Good to merge for me

2021-12-31 09:38 UTC, adamltyson approved these changes

2021-12-31 11:41 UTC, vigji requested changes
just an import to remove and then good to go!

2021-12-31 11:41 UTC, vigji commented on bg_atlasapi/config.py
>  from pkg_resources import resource_filename
this import should be removed

2021-12-31 13:38 UTC, chrisroat commented
flaked

2021-12-31 15:58 UTC, adamltyson commented
Happy to merge once @FedeClaudi has OK'd it.

2021-12-31 15:59 UTC, vigji approved these changes

2021-12-31 19:02 UTC, FedeClaudi commented
looks good to me

2021-12-31 19:02 UTC, FedeClaudi approved these changes

2021-12-31 19:03 UTC, merged