Switch to pyproject.toml
brainglobe/bg-atlasapi pull request #139
Opened 2023-02-21 16:44 UTC by dstansby

This updates the packaging to use `pyproject.toml`, following the template at https://github.com/SainsburyWellcomeCentre/python-cookiecutter. This is the first time I've (manually) applied that template to a package, so would appreciate a careful check that I've done everything right.

2023-02-22 10:53 UTC, adamltyson requested changes
Looks good. Added a few small comments.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +    "flake8",
This can be removed.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +    "bump2version",
This can be removed.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +addopts = "--cov={{cookiecutter.module_name}}"
This should specify the module name.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +    "Operating System :: MacOS :: MacOS X",
This could be simplified to `"Operating System :: OS Independent"`

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +    "black",
We can probably remove this if we're using pre-commit.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
>  target-version = ['py38', 'py39', 'py310']
Should add py311 here to match above.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +  ".bumpversion.cfg",
Can be removed.

2023-02-22 10:53 UTC, adamltyson commented on pyproject.toml
> +  ".flake8"
Can be removed.

2023-02-24 09:19 UTC, dstansby commented
Should all be fixed - I took the liberty as marking everything as resolved above as they were pretty clear cut changes.

2023-02-24 10:00 UTC, adamltyson approved these changes

2023-02-24 10:01 UTC, merged